# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170703_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripimage',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
